README.md
docs/en/fluent.md
src/Extensions/CacheKeyExtension.php
src/Extensions/FluentExtension.php
src/Models/CacheKey.php
tests/Extensions/CacheKeyExtensionTest.yml
tests/Models/CacheKeyTest.php

We were essentially already using a polymorphic relationship, just without the official config.
I don't know if it will, but if we eventually do go down the route of adding more Fluent support, having the correct polymorphic relationship **might** be useful. At this stage, it doesn't hurt to have it.

Add polymorphic relationship for CacheKey. Update Fluent docs

---

src/RelationshipGraph/Graph.php
src/Services/CacheProcessingService.php

If we track `$from` in this way, then configurations like below often do not trigger an invalidation.
```php
class SiteConfigExtensions extends DataExtension
{
private static array $has_one = [
'FacebookLink' => Link::class,
'InstagramLink' => Link::class,
];
private static array $cares = [
'FacebookLink' => Link::class,
'InstagramLink' => Link::class,
];
}
```
If we update our `InstagramLink`, then there is a chance that the first `Edge` we attempt to update is `$from: Link, $to: SiteConfig, $relation: FacebookLink`.
`updateEdge()` will end up processing an empty `DataList` as it filters `SiteConfig` on its `FacebookLinkID` field. We then mark the `Edge` as processed, so we don't "try again" when we get to `InstagramLink`.
I think `alreadyProcessed()` is the mechanism that we want to …

Don't track edges from. Rely on alreadyProcessed instead

---

.travis.yml
composer.json
src/Extensions/CacheKeyExtension.php
src/Models/CacheKey.php
src/RelationshipGraph/Graph.php
src/Services/CacheProcessingService.php
src/Services/ProcessedUpdatesService.php
tests/Extensions/CacheKeyExtensionTest.php
tests/Extensions/CacheKeyExtensionTest.yml
tests/Mocks/CaresPage.php
tests/Mocks/GlobalCaresPage.php
tests/Mocks/NoCachePage.php
tests/Mocks/TouchesPage.php
tests/RelationshipGraph/GraphTest.php

* Added some `flush()` methods to our singletons to make our unit testing life a bit easier.
* Made a few methods private/protected as they only had internal usage. Chose `protected` if I felt devs might extend the class, `private` if I thought extension was unlikely.
* Mostly I've left comments in the `Files changed`.
Checklist of tests #9 
Not saying I have 100% cov, but there's at least some level of testing.

Increase code coverage. Fixes #9

---

.github/workflows/main.yml
tests/RelationshipGraph/GraphTest.php

Increase test coverage on cached graph

---

README.md
src/RelationshipGraph/Graph.php
src/Services/CacheProcessingService.php
tests/Mocks/Models/BaseCaredHasManyModel.php
tests/Mocks/Models/BaseCaredHasOneModel.php
tests/Mocks/Models/ExtendedCaredHasManyModel.php
tests/Mocks/Models/ExtendedCaredHasOneModel.php
tests/Mocks/Pages/ExtendedCaresPage.php
tests/Mocks/Pages/ExtendedTouchedPage.php
tests/Mocks/Pages/ExtendedTouchesPage.php
tests/Scenarios/ExtendedCaresTest.php
tests/Scenarios/ExtendedCaresTest.yml

Closes #35 
Details on the bug can be found above.
The goal is for us to find any `Edge` for the `instance` `ClassName` or any ancestor that the `instance` might have.
Regarding the `$disallowList` in `getEdgesFrom()`. Technically you can have a relationship to `DataObject` if you're using a polymorphic relationship. We haven't explicitly added support for polymorphic relationships though, so I opted to leave this our for now. I'll raise an improvement story for later.

Improve support for base and extended classes

---

.github/workflows/main.yml

Some security updates are available in the latest bugfix version/s of Silverstripe Github Actions CI

Update Github Actions CI

---

README.md
src/Extensions/CacheKeyExtension.php
src/Models/CacheKey.php
src/Services/CacheProcessingService.php
tests/Models/CacheKeyTest.php

Just very light performance testing, but I created a Page with 13 different types of blocks (carousels, text, icons, etc), all with many different related records. I edited each block and then published the Page.
* Using `CacheKey::publishRecursive()` I had an average publish time of 15.85 seconds.
* Using `CacheKey::publishSingle()` I had an average publish time of 13.14 seconds.
I do not believe that we currently have a use case for the `CacheKey` model having `owns` relationships that we need to publish alongside the `CacheKey`. Switching to `publishSingle()` seems like a quick win to achieve a small (but noticeable) performance improvement.
`publish_recursive` can now be set on `CacheKey` to re-enable the original behaviour.

Use PublishSingle (by default) when publishing CacheKeys

---

phpcs.xml.dist
src/RelationshipGraph/Graph.php
src/RelationshipGraph/GraphBuildException.php
tests/RelationshipGraph/GraphBuildExceptionTest.php

Currently we throw an `Exception` as soon as we hit the first relationship error. This means that devs often run `dev/build`, fix one issue, run `dev/build` again, fix one more issue, and on and on until all errors are fixed.
Example new Exception message:
```bash
ERROR [Emergency]: Uncaught Terraformers\KeysForCache\RelationshipGraph\GraphBuildException:
No valid has_many or belongs_to found between Sheadawson\Linkable\Models\Link and App\Models\IconBlockItem for has_one relationship IconBlockLink
No valid has_many or belongs_to found between Sheadawson\Linkable\Models\Link and App\Models\ImageCarouselBlockItem for has_one relationship Link
No valid has_many or belongs_to found between Sheadawson\Linkable\Models\Link and App\Models\LinkBlockItem for has_one relationship LinkBlockItem
IN …
```

Collate build errors before throwing exception

---

src/Extensions/CacheKeyExtension.php

This was an oversight in #40. Performing a `write()` every time we fetch a `CacheKey` was/is quite costly.

Only write() CacheKey if it's not in the DB

---

README.md
docs/en/gridfield-orderable.md
src/Extensions/CacheKeyExtension.php
src/Extensions/GridFieldOrderableRowsExtension.php

`Versioned` DataObjects are supported OotB as `GridFieldOrderableRows` already saves sort orders using the `ORM` (which means that all of our triggers are already actioned). The only DataObjects that are **not** supported OotB are non `Versioned` DataObjects, as `GridFieldOrderableRows` performs SQL Queries (outside of the ORM) to update their sort orders.
I've raised a question on the GridField Extensions module to ask if we could use the ORM to save sort orders, which would mean that everything would work OotB (without this Extension) as all of our triggers would be actioned.
As such, I really do consider this Extension to be a "workaround".
I think that folks should be considering adding `Versioned` to their DataObjects. There are definitely times where you might not want them to be …

Add Extension for GridFieldOrderableRows support

---

src/Extensions/CacheKeyExtension.php

This change will have no affect on existing projects, but it allows devs to override the `triggerCacheEvent()` directly on their model (if they desire).

Trigger cache event on $owner rather than direct in extension

---

src/RelationshipGraph/Graph.php

PHP 8.1 deprecates static calls on traits.

Bugfix: Remove static call to Injectable trait

---

.github/workflows/main.yml
composer.json
docs/en/examples.md
src/Extensions/CacheKeyExtension.php
src/Services/CacheProcessingService.php

Fixes #38 
Also ended up needing to update our Github actions, and that introduced some new PostgreSQL stuff which meant I needed to update how we delete old cache keys (can't use `SQLDelete`).

DOCS: Update cache docs, github actions, global_cares

---

src/Services/CacheProcessingService.php
tests/Mocks/Models/CaredHasOneNonVersionedModel.php
tests/Mocks/Pages/CaresPage.php
tests/RelationshipGraph/GraphTest.php
tests/Scenarios/CaresTest.php
tests/Scenarios/CaresTest.yml
tests/Scenarios/GlobalCaresTest.php

* In our `updateEdge()` method, we have a check for `alreadyProcessed()` for any `has_one` relationships.
* In the `updateInstances()` method, we have a check for `alreadyProcessed()` for each record that is passed in (this covers the `has_many/many_many/etc`).
* But we were missing a check for `belongs_to`. This was/is causing a loop.
Solution:
* Move the `alreadyProcessed()` check into our `updateInstance()` method. This is the singular entry point for updating an instance, so it makes sense to just always check here.
* One exception is that I've also left this check in the `processChange()` method as well. This is because this method also handles clearing of global cares.
Side note:
* I would like to add more un Versioned tests, but I felt this was an important fix to prioritise first.

Bugfix: Fix an issue where belongs_to would trigger recursion

---

src/Services/CacheProcessingService.php

When saving a DO, type error is thrown if one of the relationships is an `UnsavedRalationList` (expects `DataList`). This change introduces a check for instance of `DataList` before processing the relations.

Handle cases where relationship is UnsavedRelationList

---

src/Extensions/GridFieldOrderableRowsExtension.php

On a non versioned dataobject, gridfieldorderablerowsextension throws deprecation warning when reordering objects:
[Deprecated] Calling static trait method SilverStripe\Core\Extensible::has_extension is deprecated, it should only be called on a class using the trait POST /admin/pages/edit/EditForm/34/field/ElementalArea/item/97/ItemEditForm/field/AccordionItems/reorder Line 78 in /var/www/mysite/www/vendor/silverstripe-terraformers/keys-for-cache/src/Extensions/GridFieldOrderableRowsExtension.php
Changing to DataObject (has trait Extensible, all gridfield objects should extend DO) fixes this. Not sure if this was introduced from php8 upgrade or the recent security patch

Resolve deprecation warning when calling static method on Extensible trait

---

src/Extensions/CacheKeyExtension.php
src/Extensions/StagingExtension.php
src/Models/CacheKey.php
src/Services/CacheProcessingService.php
src/State/StagingState.php
tests/Extensions/CacheKeyExtensionTest.php
tests/Mocks/Pages/CaresPage.php
tests/Models/CacheKeyTest.php
tests/Scenarios/CaresTest.php
tests/Scenarios/DotNotationCaresTest.php
tests/Scenarios/DotNotationTouchesTest.php
tests/Scenarios/ExtendedCaresTest.php
tests/Scenarios/ExtendedTouchesTest.php
tests/Scenarios/GlobalCaresTest.php
tests/Scenarios/TouchesTest.php
tests/State/StagingStateTest.php

Fixes #62
Closes #62
Basically related to the discovery here:
https://github.com/silverstripe/silverstripe-versioned/issues/382
If a user/author/etc is in a `LIVE` reading mode then any `write()` (to any `Versioned` `DataObject`) is essentially a publish (just without the extension hooks being triggered).
The change here is to make sure that we always retrieve and `write()` our `CacheKeys` in the expected stage.
So, for all of these, I just made my Page and Blocks output the value of `$CacheKey` into the template so that I could see what it was, and then I compared between `?stage=Stage` and `?stage=Live`.
**Test One:**
1. Publish page
2. View page in `?stage=Stage` and note CacheKey values
3. View page in `?stage=Live` and compare values
4. **Result:** As expected, they were the same …

Bugfix: Set reading mode when reading/writing CacheKeys

---

src/RelationshipGraph/Graph.php

If you created a `cares` for a relationship with dot notation, EG:
```php
private static array $has_many = [
'Links' => Link::class . '.MenuGroup',
];
private static array $cares = [
'Links',
];
```
But there was no corresponding relationship on the other end (in this case, `Link::class` was missing a `has_one`), then an `getRelationType()` would return `null`, and `Edge::__construct()` would throw an unhelpful exception because `$relationType` must be `string`.

Add error message if relationship is missing for dot notation

---

src/DataTransferObjects/CacheKeyDto.php

currently even though `$this->key` is nullable, the setter cannot set the key to `null` because of the argument type

allow setting key to null

---

README.md
docs/en/unit-testing.md

Fixes #72
Closes #72
I went the route of documentation because trying to programmatically clear the local cache of processed records is too difficult when there are so many valid entry points, and the fact that multiple entry points can (legitimately) be triggered in a row - EG: `onAfterPublish()` and `onAfterPublishRecursive()`, where we absolutely do not want to duplicate cache key invalidation.

Update documentation regarding unit testing with KFC

---

src/Services/CacheProcessingService.php
src/Services/ProcessedUpdatesService.php
tests/Services/ProcessedUpdatesServiceTest.php

Store the `ProcessedUpdateDtos` with a key so that they can be directly accessed - rather than looping through them all and checking the `ClassName`/`ID` individually.
The performance improvement is honestly negligible, but this is probably closer to "best practice".

Processed Updates Service minor performance improvement
